name: CI Pipeline

on:
   push:
    branches: [main]

jobs:
   build:
     runs-on: ubuntu-latest

   steps:
     - name: checkout repository
       uses:  actions/checkout@v3

     - name: Run system_check script
       run:|
         chmod +x system_check.sh
         ./system_check.sh
