name: Devops journey  Pipeline

on:
   push:
     branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - name: checkout repository
       uses: actions/checkout@v3

     - name: Build Docker image
        run: docker build -t satya-hello -f dockerfile1 .
    
     - name: Run docker container
        run: docker run satya-hello
      




