name: Devops journey  Pipeline

on:
   push:
     branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - name: checkout repository
       uses: actions/checkout@v3
     - name: Check docker version 
       run: docker --version 

     - name: Build docker images for calculator.go 
       run: docker build -t calculator.go -f dockerfile9 .

     - name: run docker container with input  
       run: echo "2 + 3" | docker run --rm  -i calculator.go 
