name: Devops journey  Pipeline

on:
   push:
     branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - name: checkout repository
       uses: actions/checkout@v3

     - name: Build Docker image for satya-system_check
       run: docker build -t satya-system_check -f dockerfile .

     - name: Run Docker container for satya-system_check
       run: docker run satya-system_check  

     - name: Build Docker image for system_check1
       run: docker build -t system_check1  -f dockerfile3 .    

     - name: Run docker container for system_check1
       run: docker run system_check1

     - name: Build docker image for satya-hello
       run: docker build -t satya-hello -f dockerfile1 .
     
     - name: Run docker container for satya-hello
       run: docker run satya-hello

     - name: Build docker image for sravani-image
       run: docker build -t sravani-image -f dockerfile2 .
     
     - name: Run docker container for sravani-image
       run: docker run sravani-image

   
     - name: Build Docker image for fool.py
       run: docker build -t fool.py -f dockerfile4 .

     - name: Run docker container for fool.py 
       run: docker run fool.py
