name: Devops journey  Pipeline

on:
   push:
     branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - name: checkout repository
       uses: actions/checkout@v3

     - name: Build Docker image
       run: docker build -t system_check1.sh -f dockerfile3 .    

     - name: Run docker container 
       run: docker run system_check1.sh


